dist: xenial
language: ruby
cache: bundler
rvm:
  - 2.6
before_install:
  - sudo ln -s /usr/bin/libtoolize /usr/bin/libtool
  - gem install bundler
  - sudo cp config/secrets.yml.example config/secrets.yml
